[WIP]PANDARIA: update huawei sdk version
cnrancher/kontainer-engine-driver-huawei pull request #2
Opened 2022-07-21 05:19 UTC by smallteeths

2022-08-08 07:58 UTC, Jason-ZW requested changes

2022-08-08 07:58 UTC, Jason-ZW commented on cce/client.go
> +	"time"
最好可以格式化一下

2022-08-08 07:58 UTC, Jason-ZW commented on cce/client.go
> +	state.ClusterID = *rtn.Metadata.Uid
rtn是否要做nil判断？

2022-08-08 07:58 UTC, Jason-ZW commented on cce/client.go
> +	}
这里面的时间是自己设定的还是参考官方文档给出的建议值？有什么依据么？

2022-08-08 07:58 UTC, Jason-ZW commented on cce/client.go
> +		}
这里是尝试两遍？有啥参考依据么？

2022-08-08 07:58 UTC, Jason-ZW commented on cce/k8s_client.go
> +	"k8s.io/client-go/tools/clientcmd"
同样问题

2022-08-08 07:58 UTC, Jason-ZW commented on cce/k8s_client.go
> +		Duration: int32(365),
默认1年？不知道超过1年期是否受影响？

2022-08-08 07:58 UTC, Jason-ZW commented on common/client.go
> +	"github.com/sirupsen/logrus"
格式

2022-08-08 07:58 UTC, Jason-ZW commented on network/client.go
> +	"github.com/sirupsen/logrus"
格式

2022-08-08 07:58 UTC, Jason-ZW commented on network/client.go
> +	response, err := client.ShowPublicip(request)
确认下client不需要显示关闭呗

2022-08-08 07:58 UTC, Jason-ZW commented on network/client.go
> +	secondaryDNS := "8.8.8.8"
建议这些以常量的方式声明

2022-08-08 07:58 UTC, Jason-ZW commented on network/client.go
> +	cidr := "192.168.0.0/24"
建议以常量方式声明

2022-08-08 07:58 UTC, Jason-ZW commented on go.mod
> +	github.com/rancher/rancher/pkg/client => github.com/rancher/rancher/pkg/client v0.0.0-20220308000653-f2a4147cf98d
发布正式版本之前需要再次更新

2022-08-08 07:58 UTC, Jason-ZW commented on common/job.go
> +		switch strings.ToLower(*response.Status.Phase) {
这里存在空指针风险

2022-08-08 07:58 UTC, Jason-ZW commented on common/types.go
> +	ErrorCodeInner string `json:"errorCode,omitempty"`
这块跟ErrorCode啥区别啊。是否能区分下呢？感觉名字上有歧义冲突

2022-08-08 07:58 UTC, Jason-ZW commented on common/types.go
> +	ErrorCodeInner string `json:"errorCode,omitempty"`
其他json都是小写，这块又是下划线是官方要求么？

2022-08-08 07:58 UTC, Jason-ZW commented on common/types.go
> +	}
errorInfo 和 err有什么区别？

2022-08-08 07:58 UTC, Jason-ZW commented on elb/client.go
> +	"github.com/sirupsen/logrus"
格式

2022-08-08 08:13 UTC, smallteeths commented on cce/client.go
> +	}
这里面是自己设置的时间。主要是等待这个 job 完成。这个没有官方的依据

2022-08-08 08:14 UTC, smallteeths commented on cce/client.go
> +		}
这里其实创建一次就可以，这里我是参考 cce 原来的逻辑创建两次 node 的。尝试创建两次更保准些

2022-08-08 08:15 UTC, smallteeths commented on cce/k8s_client.go
> +		Duration: int32(365),
这里每次都会重新生成

2022-08-09 01:31 UTC, smallteeths commented on common/types.go
> +	ErrorCodeInner string `json:"errorCode,omitempty"`
抱歉这个是原来 sdk 有的结构体。我这次没用这个结构体，我清理结构体的时候没用清理。我这次会给删掉

2022-08-09 01:31 UTC, smallteeths commented on common/types.go
> +	}
同上 https://github.com/cnrancher/kontainer-engine-driver-huawei/pull/2#discussion_r940799419

2022-08-09 01:40 UTC, smallteeths commented on network/client.go
> +	response, err := client.ShowPublicip(request)
官方没有显示的关闭，也是拼接 url

2022-08-09 01:54 UTC, smallteeths commented on cce/client.go
> +	state.ClusterID = *rtn.Metadata.Uid
errl != nil 的时候 rtn 是 nil。 所以判断一个 err != nil 就可以规避 rtn 为 nil 的情况。

2022-08-09 01:55 UTC, smallteeths commented on common/job.go
> +		switch strings.ToLower(*response.Status.Phase) {
done 已经添加了判断
`if response.Status.Phase == nil {
			return false, nil
		}`

2022-08-09 02:00 UTC, Jason-ZW approved these changes

2022-08-09 02:00 UTC, merged