[WIP] Update rancher/rancher version
cnrancher/kontainer-engine-driver-huawei pull request #5
Opened 2023-03-22 07:16 UTC by STARRY-S

2023-03-22 09:04 UTC, STARRY-S commented
自测创建 1.25 集群成功：
<img width="1483" alt="Screenshot 2023-03-22 at 17 04 05" src="https://user-images.githubusercontent.com/41445339/226853247-9445a26b-98c3-4b23-b4e7-1b862ed6b19c.png">
<img width="1173" alt="Screenshot 2023-03-22 at 17 04 16" src="https://user-images.githubusercontent.com/41445339/226853255-33da41f2-e3eb-4643-805e-a2bf09e535cc.png">

2023-03-23 02:59 UTC, STARRY-S commented
@Jason-ZW @smallteeths 麻烦帮忙 Review 此 PR，谢谢！

2023-03-23 03:02 UTC, smallteeths approved these changes
LGTM

2023-03-23 03:30 UTC, Jason-ZW requested changes
这个项目是否考虑优化下包括CI？不将vendor目录上传？

2023-03-23 03:30 UTC, Jason-ZW commented on go.mod
> +	github.com/rancher/rancher/pkg/client => github.com/rancher/rancher/pkg/client v0.0.0-20230124173332-bb1c35fc4258
这里为什么要对标到2.7.1？而且还是Upstream版本。

2023-03-23 03:30 UTC, Jason-ZW commented on go.mod
> +	github.com/rancher/rancher v0.0.0-20230124173332-bb1c35fc4258
同样问题

2023-03-23 04:31 UTC, STARRY-S commented on go.mod
> +	github.com/rancher/rancher/pkg/client => github.com/rancher/rancher/pkg/client v0.0.0-20230124173332-bb1c35fc4258
## 背景

Driver 的 [这里](https://github.com/cnrancher/kontainer-engine-driver-huawei/blob/master/driver/driver.go#L266 ) 使用的 `GenerateServiceAccountToken` 方法调用了 Rancher 的 [EnsureSecretForServiceAccount](https://github.com/rancher/rancher/blob/release/v2.7/pkg/kontainer-engine/drivers/util/utils.go#L98) 生成 `secret`。
本仓库之前使用的 Rancher 依赖的版本比较低，没有对 K8S 1.25 集群进行适配，因此升级依赖中的 Rancher 版本。

## 改动

Rancher 最新的 stable release 为 v2.7.1，因 Rancher 仓库不符合 go 的 Major version 规范，参考[这里](https://golang.cafe/blog/how-to-upgrade-to-a-major-version-in-go.html)，需要将依赖的版本指定为 v2.7.1 所对应的 Git Commit，因此 go.mod 中填写的为:

```
github.com/rancher/rancher v0.0.0-20230124173332-bb1c35fc4258
```

这里使用 Upstream 版本是因为 RPM GC 仓库是私有仓库，确保本仓库所使用的依赖所调用的 API 是最新的就可以，因此为 v2.7.1 版本。

2023-03-23 05:22 UTC, STARRY-S commented on go.mod
> +	github.com/rancher/rancher/pkg/client => github.com/rancher/rancher/pkg/client v0.0.0-20230124173332-bb1c35fc4258
如有不足，麻烦 @smallteeths 帮忙补充。

2023-03-23 05:23 UTC, STARRY-S commented
> 这个项目是否考虑优化下包括CI？不将vendor目录上传？

已移除了 `vendor` 文件夹。

2023-03-23 09:06 UTC, STARRY-S commented
已对 CI 部分做了改动，移除了 vendor 目录，rancher/rancher 依赖 replace 为 `github.com/cnrancher/pandaria`。 
PR 的 CI 没有通过的原因是 github_token secret 环境变量是无法在 PR 中获取的，自测是能跑通 `make ci` 的流程。

2023-03-24 02:18 UTC, Jason-ZW approved these changes
LGTM

2023-03-24 02:18 UTC, merged